src/backend/controllers/AuthController.php
<?php

namespace backend\controllers;

use Yii;
use yii\authclient\ClientInterface;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use common\models\{
    Account,
    LoginForm,
    UserAccount
};

/**
 * Class AuthController
 * @package backend\controllers
 */
class AuthController extends AppController
{
    public $layout = 'main';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return ArrayHelper::merge(
            parent::getBehaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::class,
                    'actions' => [
                        'logout' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'client' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'onAuthSuccess'],
                'successUrl' => Yii::$app->getHomeUrl() . 'accounts',
                'cancelCallback' => [$this, 'onAuthCancel'],
            ],
        ];
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * @param ClientInterface $client
     */
    public function onAuthCancel(ClientInterface $client)
    {
    }

    /**
     * @param ClientInterface $client
     * @throws \Throwable
     * @throws \yii\base\InvalidConfigException
     */
    public function onAuthSuccess(ClientInterface $client)
    {
        // Ищем аккаунт
        $account = Account::find()
            ->where([
                'type' => $client->getId(),
                'external_id' => $client->getUserId(),
            ])
            ->one();

        // Если аккаунт уже существует - обновляем
        if (!$account) {
            $account = new Account([
                'type' => $client->getId(),
                'php_class' => Account::getPhpClass($client->getId()),
                'external_id' => $client->getUserId(),
                'status' => Account::STATUS_UN_INIT,
            ]);
        } else {
            if (in_array($account->status, [Account::STATUS_DELETED, Account::STATUS_BLOCKED])) {
                $account->status = Account::STATUS_UN_INIT;
            }
        }

        $account->setAttributes([
            'php_class' => Account::getPhpClass($client->getId()),
            'external_link' => $client->getUserLink(),
            'external_title' => $client->getUserTitle(),
            'external_photo' => $client->getUserPhoto(),
            'token' => $client->getUserAccessToken(),
            'token_expires_in' => $client->getUserAccessTokenExpires(),
            'token_refresh' => $client->getUserRefreshCode(),
        ]);

        // Пытаемся сохранить в БД
        if ($account->validate()) {
            if ($account->save()) {
//                $queueClient = Yii::$app->get('queueAction')->getClient();
//                $queueClient->sendToQueue([
//                    'account' => $account->getApiAccount(),
//                    'action' => 'init'
//                ]);

                // Связываем с текущим пользователем
                $userAccount = UserAccount::findOne([
                    'id_account' => $account->getPrimaryKey(),
                    'id_user' => Yii::$app->getUser()->getIdentity()->getId(),
                ]);

                if (!$userAccount) {
                    $userAccount = new UserAccount([
                        'id_account' => $account->getPrimaryKey(),
                        'id_user' => Yii::$app->getUser()->getIdentity()->getId(),
                        'status' => Account::STATUS_UN_INIT,
                    ]);
                    $userAccount->save();
                }
            }
        } else {
            var_dump(
                $account->getAttributes(),
                $account->getErrors()
            );
        }
    }
}

src/backend/controllers/DashboardController.php
<?php

namespace backend\controllers;

/**
 * Class DashboardController
 * @package backend\controllers
 */
class DashboardController extends AppController
{
    /**
     * Displays homepage.
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
}

src/backend/controllers/UserController.php
<?php

namespace backend\controllers;

use backend\models\forms\{ConfigRedmineMembersForm, ConfigUserAuthForm, ConfigUserForm, LinkEntitiesForm};
use backend\services\EntityService;
use common\models\Entity;
use Yii;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * Class UserController
 * @package backend\controllers
 */
class UserController extends AppController
{
    /**
     * Displays homepage.
     * @return mixed
     */
    public function actionIndex()
    {
        $linkedUsers = Entity::find()
            ->where([
                'type' => Entity::TYPE_USER,
                'serviceId' => Entity::SERVICE_JIRA,
            ])->all();

        return $this->render('index', [
            'linkedUsers' => $linkedUsers,
        ]);
    }

    /**
     * @return array|string
     */
    public function actionCreate()
    {
        $formModel = new LinkEntitiesForm();

        if ($formModel->load(Yii::$app->request->post())) {
            Yii::$app->getResponse()->format = Response::FORMAT_JSON;
            return [
                'result' => $formModel->link(),
            ];
        } else {
            return $this->renderAjax('_create', [
                'jiraUsers' => (new EntityService())->getEntitiesAsMap(Entity::SERVICE_JIRA, Entity::TYPE_USER, true),
                'rmUsers' => (new EntityService())->getEntitiesAsMap(Entity::SERVICE_REDMINE, Entity::TYPE_USER, true),
                'formModel' => $formModel,
            ]);
        }
    }

    /**
     * @param $id
     * @return array|string
     */
    public function actionConfig($id)
    {
        $formModel = new ConfigUserForm([
            'serviceId' => $id
        ]);

        if ($formModel->load(Yii::$app->request->post(), '')) {
            Yii::$app->getResponse()->format = Response::FORMAT_JSON;
            return [
                'result' => $formModel->save(),
            ];
        } else {
            return $this->renderAjax('_config', [
                'users' => (new EntityService())->getEntities($id, Entity::TYPE_USER, false, false),
                'serviceId' => $id,
            ]);
        }
    }

    /**
     * @param $userId
     * @return array|string
     * @throws NotFoundHttpException
     */
    public function actionConfigAuth($userId)
    {
        $user = Entity::findOne($userId);

        if (!$user) {
            throw new NotFoundHttpException('User not found');
        }

        $formModel = new ConfigUserAuthForm([
            'userId' => $user->id,
        ]);

        if ($formModel->load(Yii::$app->request->post())) {
            $result = $formModel->save();

            Yii::$app->getResponse()->format = Response::FORMAT_JSON;
            return [
                'result' => $result,
            ];
        } else {

            return $this->renderAjax('_config-auth', [
                    'formModel' => $formModel
                ]
            );
        }
    }

}

src/backend/views/layouts/base.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

/* @var $this \yii\web\View */
/* @var $content string */

$bundle = AppAsset::register($this);

$this->params['body-class'] = array_key_exists('body-class', $this->params) ?
    $this->params['body-class']
    : null;
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?php echo Yii::$app->language ?>">
<head>
    <meta charset="<?php echo Yii::$app->charset ?>">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon.png" />

    <?php echo Html::csrfMetaTags() ?>
    <title><?php echo Html::encode($this->title) ?></title>
    <?php $this->head() ?>

</head>
<?php echo Html::beginTag('body', [
    'class' => implode(' ', [
        'sidebar-mini',
        ArrayHelper::getValue($this->params, 'body-class'),
        env('BACKEND_THEME_SKIN'),
        env('BACKEND_LAYOUT_FIXED'),
        env('BACKEND_LAYOUT_BOXED'),
        env('BACKEND_LAYOUT_COLLAPSED_SIDEBAR'),
    ])
])?>
    <?php $this->beginBody() ?>
        <?php echo $content ?>
    <?php $this->endBody() ?>
<?php echo Html::endTag('body') ?>
</html>
<?php $this->endPage() ?>

src/backend/views/layouts/common.php
<?php
/**
 * @var $this yii\web\View
 */

use common\widgets\Alert;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;
use backend\assets\AppAsset;
use backend\widgets\Menu;

$bundle = AppAsset::register($this);
$this->registerJs("var SocketServer = '" . env('SOCKET_HOST') . "';", $this::POS_HEAD);
$this->registerJs("var userAuth = '" . Yii::$app->getUser()->getIdentity()->getAuthKey() . "';", $this::POS_HEAD);
?>
<?php $this->beginContent('@backend/views/layouts/base.php'); ?>
<div class="wrapper">
    <!-- header logo: style can be found in header.less -->
    <header class="main-header">
        <a href="/" class="logo">
            <img src="/img/logo.png" height="40" class="user-image"/>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only"><?php echo Yii::t('backend', 'Toggle navigation') ?></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <span class="sockets-status">
                <i class="fa fa-refresh"></i>
            </span>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li><?= Html::a(Yii::t('backend', 'About'), ['/site/about']) ?></li>
                </ul>

                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="https://dummyimage.com/100x100/000000/fff" class="user-image">
                            <span><?php echo Yii::$app->user->identity->username ?> <i class="caret"></i></span>
                        </a>

                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header light-blue">
                                <img src="https://dummyimage.com/100x100/000000/fff" class="img-circle"
                                     alt="User Image"/>
                                <p><?php echo Yii::$app->user->identity->username ?></p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                </div>
                                <div class="pull-right">
                                    <?php echo Html::a(Yii::t('backend', 'Logout'), ['/auth/logout'], ['class' => 'btn btn-default btn-flat', 'data-method' => 'post']) ?>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="https://dummyimage.com/100x100/000000/fff" class="img-circle"/>
                </div>
                <div class="pull-left info">
                    <p><?php echo Yii::t('backend', 'Hello, {username}', ['username' => Yii::$app->user->identity->username]) ?></p>
                    <a href="<?php echo Url::to(['/sign-in/profile']) ?>">
                        <i class="fa fa-circle text-success"></i>
                        <?php echo Yii::$app->formatter->asDatetime(time()) ?>
                    </a>
                </div>
            </div>
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <?php echo Menu::widget([
                'options' => ['class' => 'sidebar-menu'],
                'linkTemplate' => '<a href="{url}">{icon}<span>{label}</span>{right-icon}{badge}</a>',
                'submenuTemplate' => "\n<ul class=\"treeview-menu\">\n{items}\n</ul>\n",
                'activateParents' => true,
                'items' => [
                    [
                        'label' => Yii::t('backend', 'Main'),
                        'options' => ['class' => 'header'],
                    ],
                    [
                        'label' => Yii::t('backend', 'Dashboard'),
                        'url' => ['/dashboard/index'],
                        'icon' => '<i class="fa fa-table"></i>',
                        'active' => Yii::$app->controller->id === 'dashboard',
                    ],
                    [
                        'label' => Yii::t('backend', 'Tasks'),
                        'url' => ['/task/index'],
                        'icon' => '<i class="fa fa-refresh"></i>',
                        'active' => Yii::$app->controller->id === 'task',
                    ],
                    [
                        'label' => Yii::t('backend', 'Timeline'),
                        'url' => ['/timeline/index'],
                        'icon' => '<i class="fa fa-tasks"></i>',
                        'active' => Yii::$app->controller->id === 'timeline',
                    ],
                    [
                        'label' => Yii::t('backend', 'Settings'),
                        'url' => '#',
                        'icon' => '<i class="fa fa-cog"></i>',
                        'options' => ['class' => 'treeview'],
                        'active' => in_array(Yii::$app->controller->id, [
                            'project',
                            'employee',
                            'user',
                        ]),
                        'items' => [
                            [
                                'label' => Yii::t('backend', 'Projects'),
                                'url' => ['/project/index'],
                                'icon' => '<i class="fa fa-caret-right"></i>',
                                'active' => Yii::$app->controller->id === 'project',
                            ],
                            [
                                'label' => Yii::t('backend', 'Users'),
                                'url' => ['/user/index'],
                                'icon' => '<i class="fa fa-caret-right"></i>',
                                'active' => Yii::$app->controller->id === 'user',
                            ],
                        ],
                    ],
                    [
                        'label' => Yii::t('backend', 'Server'),
                        'url' => '#',
                        'icon' => '<i class="fa fa-server"></i>',
                        'active' => Yii::$app->controller->id === 'server',
                        'options' => ['class' => 'treeview'],
                        'items' => [
                            [
                                'label' => Yii::t('backend', 'Info'),
                                'url' => ['/server/info'],
                                'icon' => '<i class="fa fa-caret-right"></i>',
                                'active' => Yii::$app->controller->action->id === 'info',
                            ],
                            [
                                'label' => Yii::t('backend', 'Cron'),
                                'url' => ['/server/cron'],
                                'icon' => '<i class="fa fa-caret-right"></i>',
                                'active' => Yii::$app->controller->action->id === 'cron',
                            ],
                        ],
                    ],
                ]
            ]) ?>
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Right side column. Contains the navbar and content of the page -->
    <aside class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                <?php echo $this->title ?>
                <?php if (isset($this->params['subtitle'])): ?>
                    <small><?php echo $this->params['subtitle'] ?></small>
                <?php endif; ?>
            </h1>

            <?php echo Breadcrumbs::widget([
                'tag' => 'ol',
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
        </section>

        <!-- Main content -->
        <section class="content">
            <?= Alert::widget() ?>

            <?= $content ?>
        </section><!-- /.content -->
    </aside><!-- /.right-side -->
</div><!-- ./wrapper -->
<?php $this->endContent(); ?>

src/backend/views/layouts/main.php
<?php
/**
 * @var $this yii\web\View
 */

use common\widgets\Alert;
use yii\helpers\Html;

$this->registerJs("var SocketServer = '" . env('SOCKET_HOST') . "';", $this::POS_HEAD);
$this->registerJs("var userAuth = '';", $this::POS_HEAD);

?>

<?php $this->beginContent('@backend/views/layouts/base.php'); ?>
    <div class="wrapper">
        <header class="main-header">
            <a href="/" class="logo">
                <img src="/img/logo.png" height="40" class="user-image" />
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li><?= Html::a(Yii::t('backend', 'About'), ['/site/about']) ?></li>
                    </ul>

                    <?php if(Yii::$app->user->isGuest) : ?>
                        <ul class="nav navbar-nav">
                            <li><?= Html::a(Yii::t('backend', 'Login'), ['/auth/login']) ?></li>
                            <li><?= Html::a(Yii::t('backend', 'Sign Up'), ['/auth/sign-up']) ?></li>
                        </ul>
                    <?php else :  ?>
                        <ul class="nav navbar-nav">
                            <li class="dropdown user user-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <img src="https://dummyimage.com/100x100/000000/fff" class="user-image">
                                    <span><?php echo Yii::$app->user->identity->username ?> <i class="caret"></i></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <!-- User image -->
                                    <li class="user-header light-blue">
                                        <img src="https://dummyimage.com/100x100/000000/fff" class="img-circle" alt="User Image"/>
                                        <p><?php echo Yii::$app->user->identity->username ?></p>
                                    </li>
                                    <!-- Menu Footer-->
                                    <li class="user-footer">
                                        <div class="pull-left">
                                        </div>
                                        <div class="pull-right">
                                            <?php echo Html::a(Yii::t('backend', 'Logout'), ['/auth/logout'], ['class' => 'btn btn-default btn-flat', 'data-method' => 'post']) ?>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    <?php endif; ?>
                </div>
            </nav>
        </header>

        <aside class="content-wrapper no-margin">
            <section class="content">
                <?= Alert::widget() ?>

                <?= $content ?>
            </section><!-- /.content -->
        </aside>
    </div>
<?php $this->endContent(); ?>