src/common/models/User.php
<?php

namespace common\models;

use common\models\consignment\Consignment;
use Yii;
use yii\behaviors\AttributeBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\web\IdentityInterface;

/**
 * @SWG\Definition(
 *   definition="User",
 *   type="object",
 *   allOf={
 *       @SWG\Schema(
 *           @SWG\Property( property="id", type="integer", description="ID" ),
 *           @SWG\Property( property="key", type="string", description="Уникальный строковый ключ" ),
 *           @SWG\Property( property="email", type="string", description="E-mail" ),
 *           @SWG\Property( property="first_name", type="string", description="Имя" ),
 *           @SWG\Property( property="last_name", type="string", description="Фамилия" ),
 *           @SWG\Property( property="city", type="string", description="Город" ),
 *           @SWG\Property( property="birth_date", type="string", description="Дата рождения" ),
 *           @SWG\Property( property="marital_status", type="string", description="Семейное положение" ),
 *           @SWG\Property( property="political_status", type="string", description="Политические убеждения" ),
 *           @SWG\Property( property="consignments", type="array", description="Список партий, где состоит", @SWG\Items(ref="#/definitions/Consignment") ),
 *       )
 *   }
 * )
 *
 * User model
 *
 * @property integer $id
 * @property string $key
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 * @property string $first_name // Имя
 * @property string $last_name // Фамилия
 * @property string $city // Город
 * @property string $birth_date // Дата рождения
 * @property string $marital_status // Семейное положение
 * @property string $political_status // Политические убеждения
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;

    const ROLE_USER = 'user';
    const ROLE_MANAGER = 'manager';
    const ROLE_ADMINISTRATOR = 'admin';

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'value' => new Expression('NOW()'),
            ],
            [
                'class' => AttributeBehavior::class,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => 'key',
                ],
                'value' => function ($event) {
                    return uniqid('', true);
                },
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
            ['key', 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function fields()
    {
        $fields = [
            'id',
            'email',
            'first_name',
            'last_name',
            'city',
            'birth_date',
            'marital_status',
            'political_status',
            'avatar' => function () {
                return 'https://placehold.it/100x100';
            },
            'consignments',
        ];

        if ($this->id === Yii::$app->getUser()->getIdentity()->getId()) {
            $fields = array_merge_recursive($fields, [
                'authKey',
//                'socketKey' => function () {
//                    return (new AuthService())->getJWTForCentrifuge($this);
//                },
            ]);
        }

        return $fields;
    }

    /**
     * {@inheritdoc}
     */
    public function extraFields()
    {
        return [
            'status',
            'email',
            'initiatives',
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['auth_key' => $token, 'status' => self::STATUS_ACTIVE]);
        //    throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by email
     *
     * @param $email
     * @return static|null
     */
    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int)substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * {@inheritdoc}
     */
    public function getDisplayName()
    {
        return $this->username;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     * @throws \yii\base\Exception
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    /**
     * @return \yii\db\ActiveQuery
     * @throws \yii\base\InvalidConfigException
     */
    public function getConsignments()
    {
        return $this->hasMany(Consignment::class, ['id' => 'consignment_id'])
            ->viaTable('consignment_member', ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     * @throws \yii\base\InvalidConfigException
     */
    public function getInitiatives()
    {
        return $this->hasMany(Initiative::class, ['id' => 'initiative_id'])
            ->viaTable('initiative_member', ['user_id' => 'id']);
    }
}

src/backend/controllers/UserController.php
<?php

namespace backend\controllers;

use backend\models\forms\{ConfigRedmineMembersForm, ConfigUserAuthForm, ConfigUserForm, LinkEntitiesForm};
use backend\services\EntityService;
use common\models\Entity;
use Yii;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * Class UserController
 * @package backend\controllers
 */
class UserController extends AppController
{
    /**
     * Displays homepage.
     * @return mixed
     */
    public function actionIndex()
    {
        $linkedUsers = Entity::find()
            ->where([
                'type' => Entity::TYPE_USER,
                'serviceId' => Entity::SERVICE_JIRA,
            ])->all();

        return $this->render('index', [
            'linkedUsers' => $linkedUsers,
        ]);
    }

    /**
     * @return array|string
     */
    public function actionCreate()
    {
        $formModel = new LinkEntitiesForm();

        if ($formModel->load(Yii::$app->request->post())) {
            Yii::$app->getResponse()->format = Response::FORMAT_JSON;
            return [
                'result' => $formModel->link(),
            ];
        } else {
            return $this->renderAjax('_create', [
                'jiraUsers' => (new EntityService())->getEntitiesAsMap(Entity::SERVICE_JIRA, Entity::TYPE_USER, true),
                'rmUsers' => (new EntityService())->getEntitiesAsMap(Entity::SERVICE_REDMINE, Entity::TYPE_USER, true),
                'formModel' => $formModel,
            ]);
        }
    }

    /**
     * @param $id
     * @return array|string
     */
    public function actionConfig($id)
    {
        $formModel = new ConfigUserForm([
            'serviceId' => $id
        ]);

        if ($formModel->load(Yii::$app->request->post(), '')) {
            Yii::$app->getResponse()->format = Response::FORMAT_JSON;
            return [
                'result' => $formModel->save(),
            ];
        } else {
            return $this->renderAjax('_config', [
                'users' => (new EntityService())->getEntities($id, Entity::TYPE_USER, false, false),
                'serviceId' => $id,
            ]);
        }
    }

    /**
     * @param $userId
     * @return array|string
     * @throws NotFoundHttpException
     */
    public function actionConfigAuth($userId)
    {
        $user = Entity::findOne($userId);

        if (!$user) {
            throw new NotFoundHttpException('User not found');
        }

        $formModel = new ConfigUserAuthForm([
            'userId' => $user->id,
        ]);

        if ($formModel->load(Yii::$app->request->post())) {
            $result = $formModel->save();

            Yii::$app->getResponse()->format = Response::FORMAT_JSON;
            return [
                'result' => $result,
            ];
        } else {

            return $this->renderAjax('_config-auth', [
                    'formModel' => $formModel
                ]
            );
        }
    }

}

src/backend/views/user/_config-auth.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $formModel \backend\models\forms\ConfigUserAuthForm */

?>

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><?= Yii::t('backend', 'Config for user <b>`' . $formModel->user->externalTitle . '`</b>') ?></h4>
    </div>

<?php $form = ActiveForm::begin(['id' => 'config-auth-form', 'action' => Url::toRoute(['/user/config-auth', 'userId' => $formModel->userId])]); ?>
    <div class="modal-body">
        <?= $form->field($formModel, 'login')->textInput([
            'placeholder' => 'Type login here...',
            'class' => 'form-control'
        ]) ?>
        <?= $form->field($formModel, 'password')->passwordInput([
            'placeholder' => 'Type password here...',
            'class' => 'form-control'
        ]) ?>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?= Yii::t('backend', 'Cancel') ?></button>
        <?= Html::submitButton(Yii::t('backend', 'Save'), ['class' => 'btn btn-primary',]) ?>
    </div>
<?php ActiveForm::end(); ?>

<?php
$js = <<<JS
    $('#config-auth-form').on('beforeSubmit', function(){
        var data = $(this).serialize();
        var action = $(this).attr('action');
        $.ajax({
            url: action,
            type: 'POST',
            data: data,
            success: function(res){
            console.log(res);
                location.reload();
            },
            error: function(){
                console.log('Error');
            }
        });
        return false;
    });
JS;

$this->registerJs($js);
?>

src/backend/views/user/_config.php
<?php

use common\models\Entity;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $users array */
/* @var $serviceId string */

?>

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><?= Yii::t('backend', 'All users in service <b>`' . $serviceId . '`</b>') ?></h4>
    </div>

<?php $form = ActiveForm::begin(['id' => 'config-form', 'action' => Url::toRoute(['/user/config', 'id' => $serviceId])]); ?>
    <div class="modal-body">
        <?php /**@var Entity $item */ ?>
        <?php foreach ($users as $item) : ?>
            <div class="checkbox">
                <label <?= ($item->relatedEntity) ? 'style="font-weight:bold;"' : '' ?>>
                    <input name="users[]" value="<?= $item->id ?>"
                           type="checkbox"
                        <?= ($item->status === Entity::STATUS_ACTIVE) ? 'checked' : '' ?>
                    > <?= $item->externalTitle ?>
                </label>
            </div>
        <?php endforeach; ?>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?= Yii::t('backend', 'Cancel') ?></button>
        <?= Html::submitButton(Yii::t('backend', 'Save'), ['class' => 'btn btn-primary',]) ?>
    </div>
<?php ActiveForm::end(); ?>

<?php
$js = <<<JS
    $('#config-form').on('beforeSubmit', function(){
        var data = $(this).serialize();
        var action = $(this).attr('action');
        $.ajax({
            url: action,
            type: 'POST',
            data: data,
            success: function(res){
            console.log(res);
                location.reload();
            },
            error: function(){
                console.log('Error');
            }
        });
        return false;
    });
JS;

$this->registerJs($js);
?>

src/backend/views/user/_create.php
<?php

/* @var $this \yii\web\View */
/* @var $jiraUsers array */
/* @var $rmUsers array */

/* @var $formModel \backend\models\forms\LinkEntitiesForm */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
?>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title"><?= Yii::t('backend', 'New link for users') ?></h4>
</div>

<?php $form = ActiveForm::begin(['id' => 'create-form']); ?>
    <div class="modal-body">
        <div class="row">
            <label class="col-sm-5 control-label">Jira SD User</label>
            <label class="col-sm-2 control-label">Direction</label>
            <label class="col-sm-5 control-label">Redmine User</label>
        </div>

        <div class="row">
            <div class="col-sm-5">
                <?= $form->field($formModel, 'jiraId')->dropDownList($jiraUsers, ['prompt' => 'Select user'])->label(false) ?>
            </div>

            <div class="col-sm-2 text-center" style="line-height: 34px;">
                <span class="fa fa-2x fa-angle-right"></span>
            </div>

            <div class="col-sm-5">
                <?= $form->field($formModel, 'redmineId')->dropDownList($rmUsers, ['prompt' => 'Select user'])->label(false) ?>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?= Yii::t('backend', 'Cancel') ?></button>
        <?= Html::submitButton(Yii::t('backend', 'Save'), ['class' => 'btn btn-primary',]) ?>
    </div>
<?php ActiveForm::end(); ?>

<?php
$js = <<<JS
    $('#create-form').on('beforeSubmit', function(){
        var data = $(this).serialize();
        $.ajax({
            url: '/project/create',
            type: 'POST',
            data: data,
            success: function(res){
                location.reload();
            },
            error: function(){
                console.log('Error');
            }
        });
        return false;
    });
JS;

$this->registerJs($js);
?>

src/backend/views/user/index.php
<?php

use common\models\Entity;
use yii\bootstrap\Button;
use yii\bootstrap\ButtonDropdown;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $configMenu array */
/* @var $linkedUsers array */

$this->title = Yii::t('backend', 'Linked Users');
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="row">
    <div class="col-xs-6">
        <?= Button::widget([
            'label' => Yii::t('backend', 'New link for users'),
            'options' => [
                'class' => 'btn btn-md btn-primary js-show-modal',
                'data-target' => '#users-modal',
                'data-remote' => Url::toRoute(['/user/create']),
            ],
        ]); ?>

        <?= ButtonDropdown::widget([
            'label' => Yii::t('backend', 'Config users'),
            'options' => [
                'class' => 'btn btn-md btn-default',
            ],
            'dropdown' => [
                'items' => [
                    [
                        'label' => 'Jira Service Desk',
                        'url' => '#',
                        'linkOptions' => [
                            'data-target' => '#users-modal',
                            'data-remote' => Url::toRoute(['/user/config', 'id' => Entity::SERVICE_JIRA]),
                            'class' => 'js-show-modal',
                        ],
                    ],
                    [
                        'label' => 'Redmine',
                        'url' => '#',
                        'linkOptions' => [
                            'data-target' => '#users-modal',
                            'data-remote' => Url::toRoute(['/user/config', 'id' => Entity::SERVICE_REDMINE]),
                            'class' => 'js-show-modal',
                        ],
                    ],
                ],
            ]
        ]); ?>
    </div>
</div>

<div class="row" style="margin-top:10px;">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col" style="text-align:right;">Jira SD Users</th>
                        <th>&nbsp;</th>
                        <th scope="col" style="text-align:center;" width="100">Direction</th>
                        <th>&nbsp;</th>
                        <th scope="col">Redmine Users</th>
                    </tr>
                    </thead>

                    <tbody>
                    <?php
                    /** @var Entity $item */
                    foreach ($linkedUsers as $item) : ?>
                        <?php if ($item->relatedEntity) : ?>
                            <tr>
                                <td width="50%" align="right">
                                    <b><a href="<?= $item->externalUrl ?>" target="_blank"
                                          style="line-height:30px;"><?= $item->externalTitle ?></a></b>
                                </td>
                                <td>
                                    <?= Html::button(
                                        '<i class="fa fa-cog"></i>',
                                        [
                                            'data-target' => '#users-modal',
                                            'data-remote' => Url::toRoute(['/user/config-auth', 'userId' => $item->id]),
                                            'class' => 'js-show-modal btn btn-sm btn-default',
                                        ]); ?>
                                </td>
                                <td align="center"><span class="fa fa-angle-right" style="line-height:30px;"></span>
                                </td>
                                <td>
                                    <?= Html::button(
                                        '<i class="fa fa-cog"></i>',
                                        [
                                            'data-target' => '#users-modal',
                                            'data-remote' => Url::toRoute(['/user/config-auth', 'userId' => $item->relatedEntity->id]),
                                            'class' => 'js-show-modal btn btn-sm btn-default',
                                        ]); ?>
                                </td>
                                <td width="50%">
                                    <a href="<?= $item->relatedEntity->externalUrl ?>" target="_blank"
                                       style="line-height:30px;"><?= $item->relatedEntity->externalTitle ?></a>
                                </td>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<?= Modal::widget([
    'id' => 'users-modal',
    'toggleButton' => false,
    'clientOptions' => false,
]); ?>